language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: nightly

before_script:
    - npm install
    - grunt
    - composer install

script:
    - ./vendor/bin/phpunit
